export const sessions = [
  {
    id: '1',
    type: 'safety',
    name: 'Safety DE ALL 2026 SC Session',
    status: 'Confirmed',
    date: '19 Apr 2026',
    time: '11:00 AM',
    location: 'Munich, DE',
    trainer: 'John Doe',
    learners: [
      { id: 'd1', name: 'Antonio Garcia', email: 'antonio.garcia@amazon.dsp', result: null },
      { id: 'd2', name: 'Maria López', email: 'maria.lopez@amazon.dsp', result: null },
    ],
    link: 'https://meet.google.com/abc-defg-hij',
    module: 'Safety IT All Module',
  },
  {
    id: '2',
    type: 'info',
    name: 'Information IT 2026 SC Session',
    status: 'Confirmed',
    date: '20 Apr 2026',
    time: '09:00 AM',
    location: 'Rome, IT',
    trainer: 'John Doe',
    learners: [
      { id: 'd3', name: 'Carlos Ruiz', email: 'carlos.ruiz@amazon.dsp', result: null },
      { id: 'd4', name: 'Sofia Martinez', email: 'sofia.martinez@amazon.dsp', result: null },
      { id: 'd5', name: 'Luis Fernandez', email: 'luis.fernandez@amazon.dsp', result: null },
    ],
    link: 'https://meet.google.com/xyz-uvwx-yz',
    module: 'Information Session',
  },
  {
    id: '3',
    type: 'safety',
    name: 'Safety IT ALL 2026 SC Session',
    status: 'Confirmed',
    date: '22 Apr 2026',
    time: '02:00 PM',
    location: 'Milan, IT',
    trainer: 'Maria Sanchez',
    learners: [
      { id: 'd6', name: 'Ana Torres', email: 'ana.torres@amazon.dsp', result: null },
      { id: 'd7', name: 'Pedro Gomez', email: 'pedro.gomez@amazon.dsp', result: null },
    ],
    link: 'https://meet.google.com/mno-pqrs-tu',
    module: 'Safety IT All Module',
  },
  {
    id: '7',
    type: 'info',
    name: 'Information DE 2026 SC Session',
    status: 'Assigned',
    date: '22 Apr 2026',
    time: '09:00 AM',
    location: 'Berlin, DE',
    trainer: null,
    learners: [
      { id: 'd1', name: 'Antonio Garcia', email: 'antonio.garcia@amazon.dsp', result: null },
      { id: 'd5', name: 'Luis Fernandez', email: 'luis.fernandez@amazon.dsp', result: null },
      { id: 'd8', name: 'Laura Sánchez', email: 'laura.sanchez@amazon.dsp', result: null },
    ],
    link: null,
    module: 'Information Session',
  },
  {
    id: '4',
    type: 'info',
    name: 'Information UK 2026 SC Session',
    status: 'Assigned',
    date: '24 Apr 2026',
    time: '03:30 PM',
    location: 'London, UK',
    trainer: null,
    learners: [
      { id: 'd8', name: 'Laura Sánchez', email: 'laura.sanchez@amazon.dsp', result: null },
      { id: 'd1', name: 'Antonio Garcia', email: 'antonio.garcia@amazon.dsp', result: null },
      { id: 'd3', name: 'Carlos Ruiz', email: 'carlos.ruiz@amazon.dsp', result: null },
    ],
    link: null,
    module: 'Information Session',
  },
  {
    id: '5',
    type: 'safety',
    name: 'Safety ES ALL 2025 SC Session',
    status: 'Past',
    date: '10 Jan 2026',
    time: '10:00 AM',
    location: 'Madrid, ES',
    trainer: 'John Doe',
    learners: [
      { id: 'd2', name: 'Maria López', email: 'maria.lopez@amazon.dsp', result: 'Pass' },
      { id: 'd4', name: 'Sofia Martinez', email: 'sofia.martinez@amazon.dsp', result: 'Pass' },
      { id: 'd5', name: 'Luis Fernandez', email: 'luis.fernandez@amazon.dsp', result: 'Fail' },
    ],
    link: null,
    module: 'Safety IT All Module',
  },
  {
    id: '6',
    type: 'info',
    name: 'Information FR 2025 SC Session',
    status: 'Past',
    date: '05 Feb 2026',
    time: '02:00 PM',
    location: 'Paris, FR',
    trainer: 'Maria Sanchez',
    learners: [
      { id: 'd6', name: 'Ana Torres', email: 'ana.torres@amazon.dsp', result: 'Pass' },
      { id: 'd7', name: 'Pedro Gomez', email: 'pedro.gomez@amazon.dsp', result: 'Pass' },
    ],
    link: null,
    module: 'Information Session',
  },
  {
    id: 'ses-004',
    type: 'smp',
    name: 'Amazon DE Onboarding — SMP',
    status: 'Confirmed',
    date: '01 Jul 2026',
    time: '09:00 AM',
    seats: 0,
    location: 'Online · Magic Link',
    trainer: null,
    learners: [],
    link: null,
    module: 'SMP Onboarding',
  },
]

export const certificates = [
  {
    id: 'CERT-2026-001',
    learnerId: 'hans-muller',
    learnerName: 'Hans Müller',
    learnerEmail: 'hans@amazon-de.com',
    pathId: 'path-safety-it',
    pathName: 'Safety IT All Module',
    subOrg: 'Amazon DSP Alemania',
    issuedAt: '2026-05-15',
    expiresAt: '2027-05-15',
    score: 94,
    status: 'valid',
    fileUrl: '#',
    tenantBranding: 'Amazon DE',
  },
  {
    id: 'CERT-2026-002',
    learnerId: 'klaus-weber',
    learnerName: 'Klaus Weber',
    learnerEmail: 'klaus@amazon-de.com',
    pathId: 'path-safety-it',
    pathName: 'Safety IT All Module',
    subOrg: 'Amazon DSP Alemania',
    issuedAt: '2026-05-16',
    expiresAt: '2027-05-16',
    score: 88,
    status: 'valid',
    fileUrl: '#',
    tenantBranding: 'Amazon DE',
  },
]

export const invoices = [
  {
    id: 'INV-2026-041A',
    client: 'DSP / Courier',
    org: 'Amazon DSP Alemania',
    details: 'Safety IT ALL – Madrid',
    learners: 12,
    dueDate: '02 May 2026',
    amount: 360.00,
    status: 'Pending',
    session: 'Safety IT ALL 2026 SC Session',
  },
  {
    id: 'INV-2026-039B',
    client: 'DSP / Courier',
    org: 'Amazon DSP Alemania',
    details: 'Information IT – BCN',
    learners: 15,
    dueDate: '15 Apr 2026',
    amount: 450.00,
    status: 'Paid',
    session: 'Information IT 2026 SC Session',
  },
  {
    id: 'INV-2026-038C',
    client: 'DSP / Courier',
    org: 'Amazon DSP Alemania',
    details: 'Safety Refresher',
    learners: 5,
    dueDate: '05 Apr 2026',
    amount: 150.00,
    status: 'Overdue',
    session: 'Safety Refresher 2026',
  },
  {
    id: 'INV-2026-031A',
    client: 'DSP / Courier',
    org: 'Amazon DSP Alemania',
    details: 'Safety IT ALL – Valencia',
    learners: 20,
    dueDate: '10 Mar 2026',
    amount: 600.00,
    status: 'Paid',
    session: 'Safety IT ALL Valencia 2026',
  },
  {
    id: 'INV-2026-044B',
    client: 'DHL Express',
    org: 'DHL Express DE',
    details: 'Safety DE ALL – Munich',
    learners: 18,
    dueDate: '10 May 2026',
    amount: 540.00,
    status: 'Pending',
    session: 'Safety DE ALL 2026 SC Session',
  },
  {
    id: 'INV-2026-043C',
    client: 'DHL Express',
    org: 'DHL Express DE',
    details: 'Onboarding Basics Q2',
    learners: 30,
    dueDate: '28 Apr 2026',
    amount: 900.00,
    status: 'Paid',
    session: 'Onboarding Basics 2026 SC Session',
  },
  {
    id: 'INV-2026-040D',
    client: 'Correos Express',
    org: 'Correos Express ES',
    details: 'Information ES – Sevilla',
    learners: 22,
    dueDate: '20 Apr 2026',
    amount: 660.00,
    status: 'Overdue',
    session: 'Information ES 2026 SC Session',
  },
  {
    id: 'INV-2026-036E',
    client: 'Correos Express',
    org: 'Correos Express ES',
    details: 'Safety Refresher Q1',
    learners: 10,
    dueDate: '15 Mar 2026',
    amount: 300.00,
    status: 'Paid',
    session: 'Safety Refresher Q1 2026',
  },
]

export const adminPaths = [
  { id: 1, name: 'Safety IT All Module',  org: 'Amazon DSP Alemania', profile: 'All',    acts: 3, microlessons: 12, learners: 247, completion: 92, status: 'published',  stalledDays: 14 },
  { id: 2, name: 'Information IT 2026',   org: 'Amazon DSP Alemania', profile: 'All',    acts: 2, microlessons:  8, learners:  35, completion: 89, status: 'published',  stalledDays: 14 },
  { id: 3, name: 'Onboarding Basics',     org: 'Amazon DSP Alemania', profile: 'Van',    acts: 4, microlessons: 16, learners:  15, completion:  0, status: 'draft',      stalledDays: 21 },
  { id: 4, name: 'Safety Refresher DE',   org: 'Amazon DSP Alemania', profile: 'MM',     acts: 2, microlessons:  6, learners:  52, completion: 60, status: 'inprogress', stalledDays: 14 },
  { id: 5, name: 'Road Safety Advanced',  org: 'Amazon DSP Alemania', profile: 'Hybrid', acts: 5, microlessons: 20, learners:  10, completion: 80, status: 'published',  stalledDays: 7  },
]

export const adminLearners = [
  { id: 1, name: 'Hans Müller',   email: 'hans@amazon-de.com',  org: 'Amazon DSP DE', accountStatus: 'active',     pathStatus: 'inprogress', progress: 68,  pathId: 1, pathName: 'Safety IT All Module' },
  { id: 2, name: 'Klaus Weber',   email: 'klaus@amazon-de.com', org: 'Amazon DSP DE', accountStatus: 'active',     pathStatus: 'completed',  progress: 100, pathId: 1, pathName: 'Safety IT All Module' },
  { id: 3, name: 'Anna Schmidt',  email: 'anna@amazon-de.com',  org: 'Amazon DSP DE', accountStatus: 'invited',    pathStatus: 'draft',      progress: 0,   pathId: 2, pathName: 'Information IT 2026'  },
  { id: 4, name: 'Franz Bauer',   email: 'franz@amazon-de.com', org: 'Amazon DSP DE', accountStatus: 'active',     pathStatus: 'stalled',    progress: 34,  pathId: 1, pathName: 'Safety IT All Module' },
  { id: 5, name: 'Maria Klein',   email: 'maria@amazon-de.com', org: 'Amazon DSP DE', accountStatus: 'registered', pathStatus: 'inprogress', progress: 12,  pathId: 3, pathName: 'Onboarding Basics'    },
]

export const learnersPool = [
  { id: 'd1', name: 'Antonio Garcia', email: 'antonio.garcia@amazon.dsp' },
  { id: 'd2', name: 'Maria López', email: 'maria.lopez@amazon.dsp' },
  { id: 'd3', name: 'Carlos Ruiz', email: 'carlos.ruiz@amazon.dsp' },
  { id: 'd4', name: 'Sofia Martinez', email: 'sofia.martinez@amazon.dsp' },
  { id: 'd5', name: 'Luis Fernandez', email: 'luis.fernandez@amazon.dsp' },
  { id: 'd6', name: 'Ana Torres', email: 'ana.torres@amazon.dsp' },
  { id: 'd7', name: 'Pedro Gomez', email: 'pedro.gomez@amazon.dsp' },
  { id: 'd8', name: 'Laura Sánchez', email: 'laura.sanchez@amazon.dsp' },
]

export const perksEmployers = [
  { id: 1, name: 'Globalia Travel', category: 'Travel', deals: 3, status: 'active' },
  { id: 2, name: 'Mediamarkt',      category: 'Electronics', deals: 2, status: 'active' },
  { id: 3, name: 'Mango',           category: 'Fashion', deals: 1, status: 'active' },
]

export const perksDeals = [
  { id: 1, title: '15% off flights',        employer: 'Globalia Travel', category: 'Travel',      discount: 15, validUntil: '31 Dec 2026', status: 'active' },
  { id: 2, title: 'Hotel discount 20%',     employer: 'Globalia Travel', category: 'Travel',      discount: 20, validUntil: '30 Sep 2026', status: 'active' },
  { id: 3, title: 'Vacation packages 10%',  employer: 'Globalia Travel', category: 'Travel',      discount: 10, validUntil: '31 Dec 2026', status: 'active' },
  { id: 4, title: '€50 off laptops',        employer: 'Mediamarkt',      category: 'Electronics', discount: 50, validUntil: '30 Jun 2026', status: 'active' },
  { id: 5, title: '10% off all appliances', employer: 'Mediamarkt',      category: 'Electronics', discount: 10, validUntil: '31 Aug 2026', status: 'active' },
  { id: 6, title: '25% off new collection', employer: 'Mango',           category: 'Fashion',     discount: 25, validUntil: '30 Jun 2026', status: 'active' },
]

export const perksEmployees = [
  { id: 1, name: 'Antonio Garcia',   email: 'antonio.garcia@amazon.dsp',   company: 'Amazon DSP DE', status: 'active',   enrolled: '10 Jan 2026', activeDeal: 'Hotel discount 20%' },
  { id: 2, name: 'Maria López',      email: 'maria.lopez@amazon.dsp',      company: 'Amazon DSP DE', status: 'active',   enrolled: '10 Jan 2026', activeDeal: '15% off flights' },
  { id: 3, name: 'Carlos Ruiz',      email: 'carlos.ruiz@amazon.dsp',      company: 'Amazon DSP IT', status: 'active',   enrolled: '12 Jan 2026', activeDeal: null },
  { id: 4, name: 'Sofia Martinez',   email: 'sofia.martinez@amazon.dsp',   company: 'Amazon DSP IT', status: 'invited',  enrolled: '—',           activeDeal: null },
  { id: 5, name: 'Luis Fernandez',   email: 'luis.fernandez@amazon.dsp',   company: 'Amazon DSP DE', status: 'active',   enrolled: '15 Jan 2026', activeDeal: '€50 off laptops' },
  { id: 6, name: 'Ana Torres',       email: 'ana.torres@amazon.dsp',       company: 'Amazon DSP UK', status: 'active',   enrolled: '18 Jan 2026', activeDeal: '25% off new collection' },
  { id: 7, name: 'Pedro Gomez',      email: 'pedro.gomez@amazon.dsp',      company: 'Amazon DSP DE', status: 'pending',  enrolled: '—',           activeDeal: null },
  { id: 8, name: 'Laura Sánchez',    email: 'laura.sanchez@amazon.dsp',    company: 'Amazon DSP UK', status: 'active',   enrolled: '20 Jan 2026', activeDeal: '10% off all appliances' },
]

// ── Jobs ──────────────────────────────────────────────────────────────────────

export const jobsListings = [
  {
    id: 1,
    title: 'Van Driver – Amazon DSP Munich',
    company_id: 1,
    status: 'active',
    spots_left: 3,
    location: 'Munich, DE',
    contract_type: 'Full-time',
    salary_range: [2200, 2600],
    salary_period: 'month',
    vehicle_required: 'Van',
    requirements: ['Valid EU driving licence (B)', 'Minimum 1 year driving experience', 'Right to work in Germany'],
    highlights: ['No-brainer hiring model', 'Weekly pay', 'Flexible shifts'],
    posted_date: '01 Jun 2026',
    views: 312,
    applications_count: 18,
    plan: 'PRO',
    commitment: 'No-brainer',
  },
  {
    id: 2,
    title: 'Cargo Bike Courier – City Centre Berlin',
    company_id: 1,
    status: 'active',
    spots_left: 5,
    location: 'Berlin, DE',
    contract_type: 'Part-time',
    salary_range: [14, 17],
    salary_period: 'hour',
    vehicle_required: 'Bike',
    requirements: ['Physically fit', 'Knowledge of Berlin city streets', 'Smartphone required'],
    highlights: ['Immediate start', 'Casual commitment', 'Daily pay available'],
    posted_date: '05 Jun 2026',
    views: 189,
    applications_count: 11,
    plan: 'Standard',
    commitment: 'Casual',
  },
  {
    id: 3,
    title: 'Car Courier – Amazon Flex Madrid',
    company_id: 2,
    status: 'paused',
    spots_left: 2,
    location: 'Madrid, ES',
    contract_type: 'Freelance',
    salary_range: [12, 15],
    salary_period: 'hour',
    vehicle_required: 'Car',
    requirements: ['Own vehicle (car)', 'Valid Spanish driving licence', 'Smartphone with data plan'],
    highlights: ['Smart hiring model', 'Choose your hours', 'Fuel allowance included'],
    posted_date: '20 May 2026',
    views: 97,
    applications_count: 4,
    plan: 'PRO',
    commitment: 'Smart',
  },
]

export const jobsCandidates = [
  {
    id: 1,
    name: 'Tobias Kern',
    email: 'tobias.kern@mail.de',
    phone: '+49 151 2345 6789',
    location: 'Munich, DE',
    distance_km: 4.2,
    job_id: 1,
    company_id: 1,
    funnel_stage: 'hired',
    kyc_status: 'verified',
    dvla_status: 'verified',
    right_to_work: 'verified',
    eligibility_result: 'pass',
    vehicle_type: 'Van',
    quality_tags: ['Top Rated', 'Nearby'],
    revealed: true,
    applied_date: '03 Jun 2026',
  },
  {
    id: 2,
    name: 'Lena Fischer',
    email: 'lena.fischer@mail.de',
    phone: '+49 160 9876 5432',
    location: 'Munich, DE',
    distance_km: 7.8,
    job_id: 1,
    company_id: 1,
    funnel_stage: 'delivered',
    kyc_status: 'verified',
    dvla_status: 'verified',
    right_to_work: 'pending',
    eligibility_result: 'pending',
    vehicle_type: 'Van',
    quality_tags: ['Quick Start'],
    revealed: true,
    applied_date: '04 Jun 2026',
  },
  {
    id: 3,
    name: 'Marco Ricci',
    email: 'marco.ricci@mail.de',
    phone: '+49 176 1122 3344',
    location: 'Munich, DE',
    distance_km: 12.1,
    job_id: 1,
    company_id: 1,
    funnel_stage: 'activated',
    kyc_status: 'verified',
    dvla_status: 'pending',
    right_to_work: 'verified',
    eligibility_result: 'pending',
    vehicle_type: 'Van',
    quality_tags: [],
    revealed: false,
    applied_date: '05 Jun 2026',
  },
  {
    id: 4,
    name: 'Sophie Bauer',
    email: 'sophie.bauer@mail.de',
    phone: '+49 152 5566 7788',
    location: 'Munich, DE',
    distance_km: 3.5,
    job_id: 1,
    company_id: 1,
    funnel_stage: 'raw',
    kyc_status: 'pending',
    dvla_status: 'pending',
    right_to_work: 'pending',
    eligibility_result: 'pending',
    vehicle_type: 'Van',
    quality_tags: ['Nearby'],
    revealed: false,
    applied_date: '07 Jun 2026',
  },
  {
    id: 5,
    name: 'Jan Nowak',
    email: 'jan.nowak@mail.de',
    phone: '+49 155 9900 1122',
    location: 'Berlin, DE',
    distance_km: 2.9,
    job_id: 2,
    company_id: 1,
    funnel_stage: 'hired',
    kyc_status: 'verified',
    dvla_status: 'verified',
    right_to_work: 'verified',
    eligibility_result: 'pass',
    vehicle_type: 'Bike',
    quality_tags: ['Top Rated', 'Quick Start', 'Nearby'],
    revealed: true,
    applied_date: '06 Jun 2026',
  },
  {
    id: 6,
    name: 'Amina Osei',
    email: 'amina.osei@mail.de',
    phone: '+49 157 3344 5566',
    location: 'Berlin, DE',
    distance_km: 5.4,
    job_id: 2,
    company_id: 1,
    funnel_stage: 'delivered',
    kyc_status: 'verified',
    dvla_status: 'verified',
    right_to_work: 'verified',
    eligibility_result: 'pass',
    vehicle_type: 'Bike',
    quality_tags: ['Quick Start'],
    revealed: true,
    applied_date: '07 Jun 2026',
  },
  {
    id: 7,
    name: 'Carlos Vega',
    email: 'carlos.vega@mail.es',
    phone: '+34 612 345 678',
    location: 'Madrid, ES',
    distance_km: 8.7,
    job_id: 3,
    company_id: 2,
    funnel_stage: 'activated',
    kyc_status: 'verified',
    dvla_status: 'pending',
    right_to_work: 'verified',
    eligibility_result: 'pending',
    vehicle_type: 'Car',
    quality_tags: [],
    revealed: false,
    applied_date: '24 May 2026',
  },
  {
    id: 8,
    name: 'Isabela Moreno',
    email: 'isabela.moreno@mail.es',
    phone: '+34 698 765 432',
    location: 'Madrid, ES',
    distance_km: 15.3,
    job_id: 3,
    company_id: 2,
    funnel_stage: 'raw',
    kyc_status: 'pending',
    dvla_status: 'pending',
    right_to_work: 'rejected',
    eligibility_result: 'fail',
    vehicle_type: 'Car',
    quality_tags: [],
    revealed: false,
    applied_date: '25 May 2026',
  },
]

export const jobsCompanies = [
  {
    id: 1,
    name: 'Amazon DSP DE',
    location: 'Munich, DE',
    plan: 'PRO',
    commitment: 'No-brainer',
    vehicle_type: 'Van',
    active_jobs: 2,
    pending_charges: 275.00,
    account_balance: 1200.00,
    plan_renewal_date: '01 Aug 2026',
  },
  {
    id: 2,
    name: 'Amazon Flex ES',
    location: 'Madrid, ES',
    plan: 'PRO',
    commitment: 'Smart',
    vehicle_type: 'Car',
    active_jobs: 1,
    pending_charges: 0.00,
    account_balance: 550.00,
    plan_renewal_date: '15 Jul 2026',
  },
]

export const jobsBilling = [
  {
    id: 'JB-2026-031',
    type: 'hired',
    driver_name: 'Tobias Kern',
    plan: 'PRO',
    commitment: 'No-brainer',
    vehicle_type: 'Van',
    date: '10 Jun 2026',
    amount: 275.00,
    status: 'Charged',
    city: 'Munich',
  },
  {
    id: 'JB-2026-028',
    type: 'hired',
    driver_name: 'Jan Nowak',
    plan: 'Standard',
    commitment: 'Casual',
    vehicle_type: 'Bike',
    date: '08 Jun 2026',
    amount: 149.00,
    status: 'Charged',
    city: 'Berlin',
  },
  {
    id: 'JB-2026-025',
    type: 'reveal',
    driver_name: 'Lena Fischer',
    plan: 'PRO',
    commitment: 'No-brainer',
    vehicle_type: 'Van',
    date: '05 Jun 2026',
    amount: 0.00,
    status: 'Included',
    city: 'Munich',
  },
  {
    id: 'JB-2026-019',
    type: 'renewal',
    driver_name: null,
    plan: 'PRO',
    commitment: 'No-brainer',
    vehicle_type: 'Van',
    date: '01 Jun 2026',
    amount: 199.00,
    status: 'Charged',
    city: 'Munich',
  },
  {
    id: 'JB-2026-012',
    type: 'hired',
    driver_name: 'Amina Osei',
    plan: 'Standard',
    commitment: 'Casual',
    vehicle_type: 'Bike',
    date: '15 May 2026',
    amount: 149.00,
    status: 'Overdue',
    city: 'Berlin',
  },
]

export const jobsFunnelStats = {
  raw: 24,
  activated: 18,
  delivered: 11,
  hired: 8,
  cost_per_hire: 275,
  time_to_hire_avg: 4.2,
  urgent_leads: 3,
  drop_off: {
    raw_to_activated: 25,
    activated_to_delivered: 39,
    delivered_to_hired: 27,
  },
}

export const jobsHSMQueue = [
  {
    id: 'HSM-001',
    candidate_id: 3,
    candidate_name: 'Marco Ricci',
    company_id: 1,
    company_name: 'Amazon DSP DE',
    issue_type: 'Document Rejected',
    created: '08 Jun 2026',
    status: 'Open',
    notes: 'DVLA document returned — image quality too low. Candidate asked to re-submit.',
  },
  {
    id: 'HSM-002',
    candidate_id: 8,
    candidate_name: 'Isabela Moreno',
    company_id: 2,
    company_name: 'Amazon Flex ES',
    issue_type: 'KYC Blocked',
    created: '07 Jun 2026',
    status: 'Open',
    notes: 'Right to work document flagged. Manual review required.',
  },
  {
    id: 'HSM-003',
    candidate_id: 7,
    candidate_name: 'Carlos Vega',
    company_id: 2,
    company_name: 'Amazon Flex ES',
    issue_type: 'Dispute',
    created: '06 Jun 2026',
    status: 'Open',
    notes: 'Candidate disputes DVLA check result. Claims licence is valid and current.',
  },
  {
    id: 'HSM-004',
    candidate_id: 2,
    candidate_name: 'Lena Fischer',
    company_id: 1,
    company_name: 'Amazon DSP DE',
    issue_type: 'Other',
    created: '03 Jun 2026',
    status: 'Resolved',
    notes: 'Right to work document re-submitted and approved after manual verification.',
  },
  {
    id: 'HSM-005',
    candidate_id: 4,
    candidate_name: 'Sophie Bauer',
    company_id: 1,
    company_name: 'Amazon DSP DE',
    issue_type: 'Document Rejected',
    created: '01 Jun 2026',
    status: 'Resolved',
    notes: 'KYC photo re-taken and verified successfully. Candidate moved to Activated.',
  },
]

export const driverJobs = [
  {
    id: 1,
    title: 'Van Driver – Amazon DSP Munich',
    company: 'Amazon DSP DE',
    company_logo_initial: 'A',
    location: 'Munich, DE',
    distance_km: 3.2,
    salary_amount: 2400,
    salary_period: 'month',
    highlights: ['Weekly pay', 'No-brainer model', 'Uniform provided'],
    vehicle_type: 'Van',
    urgent: true,
    schedule: 'Immediate',
    requirements_met: 4,
    image_placeholder: '#1e3a5f',
  },
  {
    id: 2,
    title: 'Cargo Bike Courier – City Centre Berlin',
    company: 'Amazon DSP DE',
    company_logo_initial: 'A',
    location: 'Berlin, DE',
    distance_km: 1.8,
    salary_amount: 15,
    salary_period: 'hour',
    highlights: ['Daily pay available', 'Flexible hours', 'Immediate start'],
    vehicle_type: 'Bike',
    urgent: false,
    schedule: 'Immediate',
    requirements_met: 3,
    image_placeholder: '#065f46',
  },
  {
    id: 3,
    title: 'Car Courier – Amazon Flex Madrid',
    company: 'Amazon Flex ES',
    company_logo_initial: 'A',
    location: 'Madrid, ES',
    distance_km: 6.1,
    salary_amount: 12,
    salary_period: 'hour',
    highlights: ['Choose your hours', 'Fuel allowance', 'Smart hiring model'],
    vehicle_type: 'Car',
    urgent: false,
    schedule: 'From 01 Jul 2026',
    requirements_met: 3,
    image_placeholder: '#7c2d12',
  },
  {
    id: 4,
    title: 'Van Driver – DSP London East',
    company: 'UK DSP Ltd',
    company_logo_initial: 'U',
    location: 'London, UK',
    distance_km: 4.5,
    salary_amount: 600,
    salary_period: 'week',
    highlights: ['Weekly pay', 'Full-time permanent', 'Paid training'],
    vehicle_type: 'Van',
    urgent: true,
    schedule: 'Immediate',
    requirements_met: 4,
    image_placeholder: '#1e1b4b',
  },
  {
    id: 5,
    title: 'Bike Rider – Paris Metro Deliveries',
    company: 'Rapid Delivery FR',
    company_logo_initial: 'R',
    location: 'Paris, FR',
    distance_km: 2.3,
    salary_amount: 13,
    salary_period: 'hour',
    highlights: ['Casual shifts', 'Tips included', 'Electric bike provided'],
    vehicle_type: 'Bike',
    urgent: false,
    schedule: 'From 15 Jul 2026',
    requirements_met: 2,
    image_placeholder: '#064e3b',
  },
]
