export const sessions = [
  {
    id: '1',
    type: 'safety',
    name: 'Safety DE ALL 2026 SC Session',
    status: 'Confirmed',
    date: '19 Apr 2026',
    time: '11:00 AM',
    location: 'Munich, DE',
    trainer: 'John Doe',
    learners: [
      { id: 'd1', name: 'Antonio Garcia', email: 'antonio.garcia@amazon.dsp', result: null },
      { id: 'd2', name: 'Maria López', email: 'maria.lopez@amazon.dsp', result: null },
    ],
    link: 'https://meet.google.com/abc-defg-hij',
    module: 'Safety IT All Module',
  },
  {
    id: '2',
    type: 'info',
    name: 'Information IT 2026 SC Session',
    status: 'Confirmed',
    date: '20 Apr 2026',
    time: '09:00 AM',
    location: 'Rome, IT',
    trainer: 'John Doe',
    learners: [
      { id: 'd3', name: 'Carlos Ruiz', email: 'carlos.ruiz@amazon.dsp', result: null },
      { id: 'd4', name: 'Sofia Martinez', email: 'sofia.martinez@amazon.dsp', result: null },
      { id: 'd5', name: 'Luis Fernandez', email: 'luis.fernandez@amazon.dsp', result: null },
    ],
    link: 'https://meet.google.com/xyz-uvwx-yz',
    module: 'Information Session',
  },
  {
    id: '3',
    type: 'safety',
    name: 'Safety IT ALL 2026 SC Session',
    status: 'Confirmed',
    date: '22 Apr 2026',
    time: '02:00 PM',
    location: 'Milan, IT',
    trainer: 'Maria Sanchez',
    learners: [
      { id: 'd6', name: 'Ana Torres', email: 'ana.torres@amazon.dsp', result: null },
      { id: 'd7', name: 'Pedro Gomez', email: 'pedro.gomez@amazon.dsp', result: null },
    ],
    link: 'https://meet.google.com/mno-pqrs-tu',
    module: 'Safety IT All Module',
  },
  {
    id: '7',
    type: 'info',
    name: 'Information DE 2026 SC Session',
    status: 'Assigned',
    date: '22 Apr 2026',
    time: '09:00 AM',
    location: 'Berlin, DE',
    trainer: null,
    learners: [
      { id: 'd1', name: 'Antonio Garcia', email: 'antonio.garcia@amazon.dsp', result: null },
      { id: 'd5', name: 'Luis Fernandez', email: 'luis.fernandez@amazon.dsp', result: null },
      { id: 'd8', name: 'Laura Sánchez', email: 'laura.sanchez@amazon.dsp', result: null },
    ],
    link: null,
    module: 'Information Session',
  },
  {
    id: '4',
    type: 'info',
    name: 'Information UK 2026 SC Session',
    status: 'Assigned',
    date: '24 Apr 2026',
    time: '03:30 PM',
    location: 'London, UK',
    trainer: null,
    learners: [
      { id: 'd8', name: 'Laura Sánchez', email: 'laura.sanchez@amazon.dsp', result: null },
      { id: 'd1', name: 'Antonio Garcia', email: 'antonio.garcia@amazon.dsp', result: null },
      { id: 'd3', name: 'Carlos Ruiz', email: 'carlos.ruiz@amazon.dsp', result: null },
    ],
    link: null,
    module: 'Information Session',
  },
  {
    id: '5',
    type: 'safety',
    name: 'Safety ES ALL 2025 SC Session',
    status: 'Past',
    date: '10 Jan 2026',
    time: '10:00 AM',
    location: 'Madrid, ES',
    trainer: 'John Doe',
    learners: [
      { id: 'd2', name: 'Maria López', email: 'maria.lopez@amazon.dsp', result: 'Pass' },
      { id: 'd4', name: 'Sofia Martinez', email: 'sofia.martinez@amazon.dsp', result: 'Pass' },
      { id: 'd5', name: 'Luis Fernandez', email: 'luis.fernandez@amazon.dsp', result: 'Fail' },
    ],
    link: null,
    module: 'Safety IT All Module',
  },
  {
    id: '6',
    type: 'info',
    name: 'Information FR 2025 SC Session',
    status: 'Past',
    date: '05 Feb 2026',
    time: '02:00 PM',
    location: 'Paris, FR',
    trainer: 'Maria Sanchez',
    learners: [
      { id: 'd6', name: 'Ana Torres', email: 'ana.torres@amazon.dsp', result: 'Pass' },
      { id: 'd7', name: 'Pedro Gomez', email: 'pedro.gomez@amazon.dsp', result: 'Pass' },
    ],
    link: null,
    module: 'Information Session',
  },
  {
    id: 'ses-004',
    type: 'smp',
    name: 'Amazon DE Onboarding — SMP',
    status: 'Confirmed',
    date: '01 Jul 2026',
    time: '09:00 AM',
    seats: 0,
    location: 'Online · Magic Link',
    trainer: null,
    learners: [],
    link: null,
    module: 'SMP Onboarding',
  },
]

export const certificates = [
  {
    id: 'CERT-2026-001',
    learnerId: 'hans-muller',
    learnerName: 'Hans Müller',
    learnerEmail: 'hans@amazon-de.com',
    pathId: 'path-safety-it',
    pathName: 'Safety IT All Module',
    subOrg: 'Amazon DSP Alemania',
    issuedAt: '2026-05-15',
    expiresAt: '2027-05-15',
    score: 94,
    status: 'valid',
    fileUrl: '#',
    tenantBranding: 'Amazon DE',
  },
  {
    id: 'CERT-2026-002',
    learnerId: 'klaus-weber',
    learnerName: 'Klaus Weber',
    learnerEmail: 'klaus@amazon-de.com',
    pathId: 'path-safety-it',
    pathName: 'Safety IT All Module',
    subOrg: 'Amazon DSP Alemania',
    issuedAt: '2026-05-16',
    expiresAt: '2027-05-16',
    score: 88,
    status: 'valid',
    fileUrl: '#',
    tenantBranding: 'Amazon DE',
  },
]

export const invoices = [
  {
    id: 'INV-2026-041A',
    client: 'DSP / Courier',
    org: 'Amazon DSP Alemania',
    details: 'Safety IT ALL – Madrid',
    learners: 12,
    dueDate: '02 May 2026',
    amount: 360.00,
    status: 'Pending',
    session: 'Safety IT ALL 2026 SC Session',
  },
  {
    id: 'INV-2026-039B',
    client: 'DSP / Courier',
    org: 'Amazon DSP Alemania',
    details: 'Information IT – BCN',
    learners: 15,
    dueDate: '15 Apr 2026',
    amount: 450.00,
    status: 'Paid',
    session: 'Information IT 2026 SC Session',
  },
  {
    id: 'INV-2026-038C',
    client: 'DSP / Courier',
    org: 'Amazon DSP Alemania',
    details: 'Safety Refresher',
    learners: 5,
    dueDate: '05 Apr 2026',
    amount: 150.00,
    status: 'Overdue',
    session: 'Safety Refresher 2026',
  },
  {
    id: 'INV-2026-031A',
    client: 'DSP / Courier',
    org: 'Amazon DSP Alemania',
    details: 'Safety IT ALL – Valencia',
    learners: 20,
    dueDate: '10 Mar 2026',
    amount: 600.00,
    status: 'Paid',
    session: 'Safety IT ALL Valencia 2026',
  },
  {
    id: 'INV-2026-044B',
    client: 'DHL Express',
    org: 'DHL Express DE',
    details: 'Safety DE ALL – Munich',
    learners: 18,
    dueDate: '10 May 2026',
    amount: 540.00,
    status: 'Pending',
    session: 'Safety DE ALL 2026 SC Session',
  },
  {
    id: 'INV-2026-043C',
    client: 'DHL Express',
    org: 'DHL Express DE',
    details: 'Onboarding Basics Q2',
    learners: 30,
    dueDate: '28 Apr 2026',
    amount: 900.00,
    status: 'Paid',
    session: 'Onboarding Basics 2026 SC Session',
  },
  {
    id: 'INV-2026-040D',
    client: 'Correos Express',
    org: 'Correos Express ES',
    details: 'Information ES – Sevilla',
    learners: 22,
    dueDate: '20 Apr 2026',
    amount: 660.00,
    status: 'Overdue',
    session: 'Information ES 2026 SC Session',
  },
  {
    id: 'INV-2026-036E',
    client: 'Correos Express',
    org: 'Correos Express ES',
    details: 'Safety Refresher Q1',
    learners: 10,
    dueDate: '15 Mar 2026',
    amount: 300.00,
    status: 'Paid',
    session: 'Safety Refresher Q1 2026',
  },
]

export const adminPaths = [
  { id: 1, name: 'Safety IT All Module',  org: 'Amazon DSP Alemania', profile: 'All',    acts: 3, microlessons: 12, learners: 247, completion: 92, status: 'published',  stalledDays: 14 },
  { id: 2, name: 'Information IT 2026',   org: 'Amazon DSP Alemania', profile: 'All',    acts: 2, microlessons:  8, learners:  35, completion: 89, status: 'published',  stalledDays: 14 },
  { id: 3, name: 'Onboarding Basics',     org: 'Amazon DSP Alemania', profile: 'Van',    acts: 4, microlessons: 16, learners:  15, completion:  0, status: 'draft',      stalledDays: 21 },
  { id: 4, name: 'Safety Refresher DE',   org: 'Amazon DSP Alemania', profile: 'MM',     acts: 2, microlessons:  6, learners:  52, completion: 60, status: 'inprogress', stalledDays: 14 },
  { id: 5, name: 'Road Safety Advanced',  org: 'Amazon DSP Alemania', profile: 'Hybrid', acts: 5, microlessons: 20, learners:  10, completion: 80, status: 'published',  stalledDays: 7  },
]

export const adminLearners = [
  { id: 1, name: 'Hans Müller',   email: 'hans@amazon-de.com',  org: 'Amazon DSP DE', accountStatus: 'active',     pathStatus: 'inprogress', progress: 68,  pathId: 1, pathName: 'Safety IT All Module' },
  { id: 2, name: 'Klaus Weber',   email: 'klaus@amazon-de.com', org: 'Amazon DSP DE', accountStatus: 'active',     pathStatus: 'completed',  progress: 100, pathId: 1, pathName: 'Safety IT All Module' },
  { id: 3, name: 'Anna Schmidt',  email: 'anna@amazon-de.com',  org: 'Amazon DSP DE', accountStatus: 'invited',    pathStatus: 'draft',      progress: 0,   pathId: 2, pathName: 'Information IT 2026'  },
  { id: 4, name: 'Franz Bauer',   email: 'franz@amazon-de.com', org: 'Amazon DSP DE', accountStatus: 'active',     pathStatus: 'stalled',    progress: 34,  pathId: 1, pathName: 'Safety IT All Module' },
  { id: 5, name: 'Maria Klein',   email: 'maria@amazon-de.com', org: 'Amazon DSP DE', accountStatus: 'registered', pathStatus: 'inprogress', progress: 12,  pathId: 3, pathName: 'Onboarding Basics'    },
]

export const learnersPool = [
  { id: 'd1', name: 'Antonio Garcia', email: 'antonio.garcia@amazon.dsp' },
  { id: 'd2', name: 'Maria López', email: 'maria.lopez@amazon.dsp' },
  { id: 'd3', name: 'Carlos Ruiz', email: 'carlos.ruiz@amazon.dsp' },
  { id: 'd4', name: 'Sofia Martinez', email: 'sofia.martinez@amazon.dsp' },
  { id: 'd5', name: 'Luis Fernandez', email: 'luis.fernandez@amazon.dsp' },
  { id: 'd6', name: 'Ana Torres', email: 'ana.torres@amazon.dsp' },
  { id: 'd7', name: 'Pedro Gomez', email: 'pedro.gomez@amazon.dsp' },
  { id: 'd8', name: 'Laura Sánchez', email: 'laura.sanchez@amazon.dsp' },
]
